language: bash
services: docker
before_install:
  - cd C:\Users\bruno\eclipse-workspace
  - echo "We aew in the docker folder"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push bwlobao/mysql-fretemais-api;
    docker push bwlobao/fretemais-api;
  on:
    branch: master
notifications:
  email: false