version: '3.9'
services:
  db:
    image: mysql:8.0.23
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: fretemais-api
    ports:
      - "3308:3306"
    networks: 
      - fretemais-network
  fretemais-app:
    image: bwlobao/fretemais-api
    restart: always
    build: .
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    ports: 
      - "8080:8080"
      - "80:8080"
    command: mvn package spring-boot:run
    links: 
      - db
    depends_on: 
      - db
    networks: 
      - fretemais-network
networks:
    fretemais-network:
        driver: bridge